//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_Ed_Services.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\bin\\Debug\\TAfeDB.sdf")]
        public string TAfeDBConnectionString {
            get {
                return ((string)(this["TAfeDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=C:\\Users\\dalevanh\\Desktop\\Libs.mdf;Inte" +
            "grated Security=True;Connect Timeout=30;User Instance=True")]
        public string LibsConnectionString {
            get {
                return ((string)(this["LibsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=C:\\Users\\dalevanh\\Desktop\\TafeDB.mdf;In" +
            "tegrated Security=True;Connect Timeout=30;User Instance=True")]
        public string TafeDBConnectionString1 {
            get {
                return ((string)(this["TafeDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\TafeDB.mdf;In" +
            "tegrated Security=True")]
        public string TafeDBConnectionString2 {
            get {
                return ((string)(this["TafeDBConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=""C:\USERS\DALEVANH.000\ONEDRIVE\TAFE\TAFE ARCHIVE\6CLP\6CLP ASSIGNMENT SPECS_AND RESOURCES\ABC ED SERVICES\TAFEDB.MDF"";Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string C__USERS_DALEVANH_000_ONEDRIVE_TAFE_TAFE_ARCHIVE_6CLP_6CLP_ASSIGNMENT_SPECS_AND_RESOURCES_ABC_ED_SERVICES_TAFEDB_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_DALEVANH_000_ONEDRIVE_TAFE_TAFE_ARCHIVE_6CLP_6CLP_ASSIGNMENT_SPECS_AND_R" +
                    "ESOURCES_ABC_ED_SERVICES_TAFEDB_MDFConnectionString"]));
            }
        }
    }
}
